### ISSUE TITLE
Fonts not rendering on Storybook

### ISSUE THREAD

**Issue by harrymansworth** [newsuk/times-paywall-components#27]
Due to issues with integrating components into render when compiled down to ES5 fonts have been disabled on Storybook. We will need to fix this in our initial tech-debt sprint.

**Comment by chrishutchinson** [comment]
A thought on this, assuming the components are using the same font family names as `render`, you can just use Storybook's [custom `<head>` tag](https://storybook.js.org/docs/configurations/add-custom-head-tags/) functionality to add the following each Story:

```html
<link rel="stylesheet" href="https://www.thetimes.co.uk/d/styles/main.min.css" />
```

You _might_ get CORS errors with that URL though, so if so, the Editorial Tools team maintain a proxy version: https://timesproxy.tools.news/d/styles/main.min.css

**Comment by harrymansworth** [comment]
Closing; Ref #32
